import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Award, CalendarCheck, Clock, ShieldCheck, Star, Users } from "lucide-react";

const doctors = [
  { id: 1, name: "Dr. John Carter", specialty: "Senior Cardiologist", experience: "15+ years", qualification: "MBBS, MD (Cardiology), FACC", image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=900", rating: 4.9, patients: "2,450+", available: true, bio: "Interventional cardiology, preventive heart care, and complex cardiac procedures." },
  { id: 2, name: "Dr. Sarah Williams", specialty: "Neurologist", experience: "12+ years", qualification: "MBBS, DM (Neurology), FRCP", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=900", rating: 4.8, patients: "1,890+", available: true, bio: "Stroke management, epilepsy care, and neurodegenerative conditions." },
  { id: 3, name: "Dr. Michael Smith", specialty: "Pediatrician", experience: "10+ years", qualification: "MBBS, MD (Pediatrics), Neonatology", image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=900", rating: 4.9, patients: "3,100+", available: true, bio: "Dedicated child healthcare, from neonatology to developmental pediatrics." },
  { id: 4, name: "Dr. Emily Brown", specialty: "Orthopedic Surgeon", experience: "14+ years", qualification: "MBBS, MS (Orthopedics), MCh", image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=900", rating: 4.7, patients: "1,650+", available: false, bio: "Joint replacement, sports injuries, and minimally invasive orthopedic surgery." },
  { id: 5, name: "Dr. Mary Khan", specialty: "Gynecologist & Obstetrician", experience: "11+ years", qualification: "MBBS, MS (OBGYN), FMAS", image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=900", rating: 4.9, patients: "2,800+", available: true, bio: "Women's health, high-risk pregnancy, and laparoscopic gynaecological surgery." },
  { id: 6, name: "Dr. Rodriguez Martin", specialty: "General Physician", experience: "18+ years", qualification: "MBBS, MD (Internal Medicine)", image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=900", rating: 4.8, patients: "4,200+", available: true, bio: "Holistic primary care and long-term management of chronic conditions." },
];

const Doctors = () => <section id="doctors" className="overflow-hidden bg-white py-24"><div className="mx-auto max-w-7xl px-6">
  <motion.header className="mx-auto max-w-3xl text-center" initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
    <p className="inline-flex items-center gap-2 rounded-full bg-lemon/20 px-4 py-2 text-sm font-semibold text-darkBlue"><ShieldCheck size={17} /> Trusted medical specialists</p>
    <h1 className="mt-6 text-4xl font-bold text-darkBlue md:text-6xl">Meet our <span className="text-green-600">expert doctors.</span></h1>
    <p className="mt-5 text-lg leading-relaxed text-gray-600">Highly qualified clinicians combining modern medicine with personal, compassionate care.</p>
  </motion.header>
  <div className="mt-16 grid gap-8 md:grid-cols-2 xl:grid-cols-3">{doctors.map((doctor, index) => <DoctorCard key={doctor.id} doctor={doctor} index={index} />)}</div>
  <section className="mt-20 grid gap-8 rounded-[2.5rem] bg-darkBlue p-10 text-center text-white sm:grid-cols-2 lg:grid-cols-4">{[['50+', 'Specialists'], ['20k+', 'Patients served'], ['15+', 'Departments'], ['24/7', 'Medical support']].map(([number, label]) => <div key={label}><p className="text-4xl font-bold text-lemon">{number}</p><p className="mt-2 text-gray-300">{label}</p></div>)}</section>
  <div className="mt-16 text-center"><p className="text-lg text-gray-600">Need specialist care? <strong className="text-darkBlue">Book an appointment today.</strong></p><Link to="/appointment" className="mt-7 inline-flex items-center gap-2 rounded-full bg-darkBlue px-7 py-4 font-semibold text-white transition hover:bg-lemon hover:text-darkBlue">Book an appointment <CalendarCheck size={19} /></Link></div>
</div></section>;

function DoctorCard({ doctor, index }) { return <motion.article initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} whileHover={{ y: -8 }} className="group overflow-hidden rounded-[2rem] border border-gray-100 bg-white shadow-lg transition-shadow hover:shadow-2xl"><div className="relative h-72 overflow-hidden"><img src={doctor.image} alt={doctor.name} className="h-full w-full object-cover object-top transition duration-700 group-hover:scale-110" /><span className="absolute right-4 top-4 inline-flex items-center gap-1 rounded-full bg-white/95 px-3 py-1.5 text-sm font-bold text-darkBlue shadow"><Star size={15} className="fill-yellow-400 text-yellow-400" />{doctor.rating}</span><span className={`absolute bottom-4 left-4 inline-flex items-center gap-1 rounded-full px-3 py-1.5 text-sm font-semibold text-white ${doctor.available ? "bg-green-600" : "bg-gray-600"}`}><ShieldCheck size={15} />{doctor.available ? "Available today" : "Currently busy"}</span></div><div className="p-7"><h2 className="text-2xl font-bold text-darkBlue">{doctor.name}</h2><p className="mt-1 font-semibold text-green-600">{doctor.specialty}</p><div className="mt-5 space-y-2 text-sm text-gray-600"><p className="flex items-center gap-2"><Clock size={16} />{doctor.experience} experience</p><p className="flex items-center gap-2"><Users size={16} />{doctor.patients} patients treated</p></div><p className="mt-5 flex gap-2 rounded-2xl bg-gray-50 p-3 text-xs font-medium text-gray-600"><Award size={19} className="shrink-0 text-green-600" />{doctor.qualification}</p><p className="mt-5 line-clamp-2 leading-relaxed text-gray-600">{doctor.bio}</p><div className="mt-7 grid grid-cols-2 gap-3"><Link to="/appointment" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-darkBlue px-3 py-3 font-semibold text-white transition hover:bg-lemon hover:text-darkBlue"><CalendarCheck size={17} />Book</Link><Link to={`/doctors/${doctor.id}`} className="inline-flex items-center justify-center rounded-2xl border border-darkBlue px-3 py-3 font-semibold text-darkBlue transition hover:bg-darkBlue hover:text-white">Profile</Link></div></div></motion.article>; }

export default Doctors;
